apiVersion: v1
kind: Service
metadata:
  name: patient-service
  labels:
    app: patient-service
spec:
  type: LoadBalancer
  ports:
  - port: 3002
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: patient-service
