apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  labels:
    app: appointment-service
spec:
  type: LoadBalancer
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app: appointment-service
