apiVersion: v1
kind: Secret
metadata:
  name: redshift-secret
type: Opaque
data:
  database: YOUR_BASE64_ENCODED_DATABASE_NAME
  secret_arn: YOUR_BASE64_ENCODED_SECRET_ARN
  cluster_identifier: YOUR_BASE64_ENCODED_CLUSTER_IDENTIFIER
