apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  labels:
    app: ingestion-service
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ingestion-service
