apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: # base64 encoded AWS access key
  AWS_SECRET_ACCESS_KEY: # base64 encoded AWS secret key
  AWS_REGION: # base64 encoded region (e.g., ZXUtbm9ydGgtMQ== for eu-north-1)
