apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/doctors/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: doctor-service
            port:
              number: 3001
      - path: /api/patients/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: patient-service
            port:
              number: 3002
      - path: /api/appointments/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: appointment-service
            port:
              number: 3000
