apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  labels:
    app: doctor-service
spec:
  type: LoadBalancer
  ports:
  - port: 3001
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: doctor-service
