apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-aggregator
spec:
  schedule: "*/5 * * * *"  # Run at 1 AM every day
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 600  # Job must start within 10 minutes of scheduled time
  jobTemplate:
    spec:
      backoffLimit: 3  # Retry failed jobs up to 3 times
      activeDeadlineSeconds: 1800  # Job timeout after 30 minutes
      template:
        spec:
          containers:
          - name: aggregator
            image: minurijayasooriya97/aggregator-service:IMAGE_VERSION
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
            env:
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: REDSHIFT_DATABASE
              valueFrom:
                secretKeyRef:
                  name: redshift-secret
                  key: REDSHIFT_DATABASE
            - name: REDSHIFT_SECRET_ARN
              valueFrom:
                secretKeyRef:
                  name: redshift-secret
                  key: REDSHIFT_SECRET_ARN
            - name: REDSHIFT_WORKGROUP_NAME
              valueFrom:
                secretKeyRef:
                  name: redshift-secret
                  key: REDSHIFT_WORKGROUP_NAME
          restartPolicy: OnFailure
