name: Build and Deploy Images to Docker Hub

on:
  push:
    branches:
      - main # Set a branch to deploy when pushed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          'appointment-service',
          'doctor-service',
          'patient-service',
          'ingestion-service',
          'aggregator-service'
        ]
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: |
            minurijayasooriya97/${{ matrix.service }}:latest
            minurijayasooriya97/${{ matrix.service }}:${{ github.sha }}
          cache-from: type=registry,ref=minurijayasooriya97/${{ matrix.service }}:latest
          cache-to: type=inline
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
